# Name of your site. Used to uniquely configure containers.
service: najlepsza_demokracja

# Name of the container image.
image: meceo/najlepsza_demokracja

# Use GIT_URL from env to auto-update site via git pulls.
# Remember to run `kamal env push` after making changes!
env:
  secret:
    - GIT_URL

# Credentials for your image host.
registry:
  server: ghcr.io
  username: meceo
  password:
    - SKIFF_REGISTRY_PASSWORD

# Check /up against 80
healthcheck:
  port: 80
# Use a different ssh user than root
# ssh:
#   user: app
